### ISSUE TITLE
Bug: can't handle missing font file found in CSS

### ISSUE THREAD

**Issue by samnung** [epuber-io/epuber#106]
CSS:

```css
@font-face {
  font-family: Bookerly;
  font-style: italic;
  font-weight: bold;
  src: url("../fonts/Bookerly/Bookerly-BoldItalic.ttf");
}
```

The file at `../fonts/Bookerly/Bookerly-BoldItalic.ttf` does not exist.
